Use strategy instead of accelerator in pl
GT4SD/gt4sd-core pull request #136
Opened 2022-09-09 11:17 UTC by christofid

2022-09-09 16:39 UTC, drugilsberg commented
@christofid feel free to convert to ready for review once you think it's ready

2022-09-12 13:08 UTC, drugilsberg requested changes
See comment

2022-09-12 13:08 UTC, drugilsberg commented on requirements.txt
> +pytorch_lightning==1.5.0
this is a bit too stringent, is there a way to work around this?

2022-09-12 13:08 UTC, drugilsberg commented on requirements.txt
> +pytorch_lightning==1.5.0
maybe with conditional blocks based on the lightning version?

2022-10-07 13:42 UTC, georgosgeorgos commented
https://github.com/GT4SD/gt4sd-core/pull/149

2022-10-07 14:06 UTC, drugilsberg commented
Closing in favour of #149

2022-10-07 14:06 UTC, closed without merging