chore: figures
GT4SD/gt4sd-core pull request #141
Opened 2022-09-25 14:02 UTC by georgosgeorgos

* Add figures README.
     * Case study.  
     * Graphical abstract for discovery workflow.

* Add figures to main docs.

2022-09-25 15:48 UTC, jannisborn approved these changes
Very nice, great proactivity, I just suggested some comestics for the readme formatting

2022-09-25 15:48 UTC, jannisborn commented on README.md
> +<img src="./docs/_static/gt4sd_logo.png" alt="logo" width="300"/>
```suggestion
<img align="right" width="200" height="200" src="./docs/_static/gt4sd_logo.png" alt="logo">
```

2022-09-25 15:48 UTC, jannisborn commented on README.md
> +<img src="./docs/_static/gt4sd_case_study.png" alt="logo" width="500"/>
```suggestion
<p align="center">
	<img src="./docs/_static/gt4sd_case_study.png" alt="photo not available" width="100%" height="100%">
</p>```

2022-09-27 09:07 UTC, drugilsberg reviewed
I would consider removing the logo and swapping the order of the case study and the main figure. Also the resolution is not amazing, so we could reduce a bit the size of the images.

2022-09-27 09:25 UTC, georgosgeorgos commented
> I would consider removing the logo and swapping the order of the case study and the main figure. Also the resolution is not amazing, so we could reduce a bit the size of the images.

For the resolution: I converted pdf to png. Not sure if we can use the pdf directly in markdown.

2022-09-27 14:16 UTC, drugilsberg requested changes
Structure looks good, but image quality is terrible. How many DPIs are we using here?

2022-09-27 16:33 UTC, drugilsberg reviewed
To me it looks really good, but I see a problem with mypy now, maybe some library has been updated in the meanwhile.

2022-09-28 09:51 UTC, drugilsberg approved these changes
🚀

2022-09-28 09:51 UTC, merged