Submission fixes
GT4SD/gt4sd-core pull request #167
Opened 2022-11-14 17:59 UTC by jannisborn

- Miscellaneous fixes in notebooks for submission
- improved error handling and documentation in RT

2022-11-15 21:32 UTC, drugilsberg requested changes
Great job, only minor changes

2022-11-15 21:32 UTC, drugilsberg commented on src/gt4sd/algorithms/core.py
> +from ..exceptions import Gt4sdTimeoutError, InvalidItem, S3SyncError, SamplingError
```suggestion
from ..exceptions import GT4SDTimeoutError, InvalidItem, S3SyncError, SamplingError
```

2022-11-15 21:32 UTC, drugilsberg commented on src/gt4sd/algorithms/core.py
> +        raise Gt4sdTimeoutError(
```suggestion
        raise GT4SDTimeoutError(
```

2022-11-15 21:32 UTC, drugilsberg commented on src/gt4sd/algorithms/core.py
> +        except Gt4sdTimeoutError:
```suggestion
        except GT4SDTimeoutError:
```

2022-11-15 21:32 UTC, drugilsberg commented on src/gt4sd/exceptions.py
> +class Gt4sdTimeoutError(TimeoutError):
```suggestion
class GT4SDTimeoutError(TimeoutError):
```

2022-11-15 21:44 UTC, drugilsberg reviewed
Looks good, I would consider cleaning the notebooks output before merging.

2022-11-15 21:44 UTC, jannisborn commented
We need this additional exception class because `SamplingError` is a child of the native `TimeoutError` and thus the `except TimeoutError:` block is entered not only if a `TimeoutError` has been raised but also if a `SamplingError` was raised. This led to wrong error messages

2022-11-15 21:46 UTC, drugilsberg commented
> We need this additional exception class because `SamplingError` is a child of the native `TimeoutError` and thus the `except TimeoutError:` block is entered not only if a `TimeoutError` has been raised but also if a `SamplingError` was raised. This led to wrong error messages

Makes sense, this was a good catch.

2022-11-16 08:45 UTC, drugilsberg approved these changes

2022-11-16 17:26 UTC, jannisborn commented
New improvements:
[refactor: remove .core from inits](https://github.com/GT4SD/gt4sd-core/pull/167/commits/8994a421bfc430a9294a518c9aee5c80edaf968e)
[fix: torchdrug openMP mismatch](https://github.com/GT4SD/gt4sd-core/pull/167/commits/9d61854f9bdbd6f3b6e3c54a95606cff4d4003b0)
[refactor: avoid signal to run core outside main thread](https://github.com/GT4SD/gt4sd-core/pull/167/commits/3ef6f4d7b521738c8575981b959a2f7b3911d038)

2022-11-16 18:24 UTC, drugilsberg approved these changes
Looks great only minor suggestions for typing and docstring in the timeout function.

2022-11-16 18:24 UTC, drugilsberg commented on src/gt4sd/algorithms/core.py
> +    def timeout(self, item_set: Set, detail: str, error: TimeoutError):
```suggestion
    def timeout(self, item_set: Set, detail: str, error: TimeoutError) -> None:
```

2022-11-16 18:24 UTC, drugilsberg commented on src/gt4sd/algorithms/core.py
> +
```suggestion
```

2022-11-16 21:39 UTC, jannisborn commented on src/gt4sd/algorithms/core.py
> +            detail: context or condition for the generation. Defaults to None.
```suggestion
            detail: context or condition for the generation.
```

2022-11-17 07:23 UTC, merged