Enable T5 generation and beam search
GT4SD/gt4sd-core pull request #201
Opened 2023-02-16 12:57 UTC by christofid

2023-02-16 13:42 UTC, drugilsberg requested changes
minor changes

2023-02-16 13:42 UTC, drugilsberg commented on src/gt4sd/algorithms/generation/tests/test_hugging_face.py
> +            marks=pytest.mark.skipif(test_settings.gt4sd_ci, reason="high_memory"),
I would not skip the test

```suggestion
            marks=pytest.mark.skipif(test_settings.gt4sd_ci, reason="high_memory")
```

2023-02-16 13:42 UTC, drugilsberg commented on src/gt4sd/algorithms/generation/hugging_face/implementation.py
> +    "t5": (AutoModelForSeq2SeqLM, AutoTokenizer, None),
should we consider using another key name as it seems more generic than t5, maybe auto-seq2seq-lm?

2023-02-16 15:00 UTC, christofid commented
Thanks @drugilsberg, I addressed these comments

2023-02-16 15:41 UTC, drugilsberg reviewed
Last small comment

2023-02-16 15:48 UTC, drugilsberg commented on src/gt4sd/algorithms/generation/tests/test_hugging_face.py
> +        pytest.param(HuggingFaceSeq2SeqGenerator, HuggingFaceGenerationAlgorithm),
here I would enable only the last one (using t5-small), sorry if I confused you

2023-02-16 16:26 UTC, drugilsberg commented on src/gt4sd/algorithms/generation/hugging_face/implementation.py
> +            self.length = adjust_length_to_model(self.length, 512)
would it be possible to infer that 512 somehow? That hardcoding worries me.

2023-02-17 10:25 UTC, drugilsberg approved these changes
LGTM

2023-02-17 14:27 UTC, merged