refactor & fix: re-organized the scripts in Enzeptional and added a test script
GT4SD/gt4sd-core pull request #61
Opened 2022-04-08 12:14 UTC by yvesnana

2022-04-08 16:13 UTC, drugilsberg requested changes
Left some comments, in general we are going in the right direction but we need to refactor a bit more. Besides the comments here additional things to consider before merging:
- unit tests with pytests have to be written, on for each file where we have tests (they will replace the single `test_enzeptional.py`).
- path to files have to be replaced with `pkg_resources` and the files added to `setup.cfg` to be tracked.
- let's rename the scorer in the tests folder to `scorer.pkl`.

2022-04-08 16:13 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +def merge_dictionaries(lst_Dict):
`lst_Dict` mixes snake and camel case, for variables and methods we use snake, so `list_of_dictionaries` would be best.
Also add docstring.

2022-04-08 16:13 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +        encoder_embedding = embedding[2].cpu().numpy()
could we conditionally select cpu or gpu here.

2022-04-08 16:13 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +        self.model = AutoModelForMaskedLM.from_pretrained(tokenizer_name)
out of curiosity, why changing this here?

2022-04-08 16:13 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +    """Selecte the top K mutated sequences based on the score
check the docstrings there are typos, K should be lower case and we also have to report the default.

2022-04-08 16:13 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +def crossover(p1, p2):
typing missing

2022-04-08 16:13 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +    """Selecte the top K mutated sequences based on the score
typing missing

2022-04-19 14:30 UTC, yvesnana commented on src/gt4sd/frameworks/enzeptional/genetic_algorithm.py
> +                if (
That's true. My only issue here is that I would like not to call/load the models multiple times

2022-04-20 07:18 UTC, drugilsberg requested changes
See my comments, there is still some open points that need to be addressed.

Also, rename: `src/gt4sd/frameworks/enzeptional/tests/small_exmaple_ProtTrans_scorrer.pkl` to `src/gt4sd/frameworks/enzeptional/tests/scorer.pkl`.
And remember to add both the scorer and `mutation_scheme.json` to `setup.cfg`.

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/genetic_algorithm.py
> +        if self.protein_embedding == "ProtTransXL" in str(type(self.protein_embedding)):
this need to be changed, `self.protein_embedding` should be a `StringEmbedding` class, then everything should become consistent.

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/genetic_algorithm.py
> +                if "ProtTransXL" in str(type(self.protein_embedding)):
same comment as above

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +    """Embed a string representation of a molecule using a ProtTrans_XLnet model"""
are we sure the docstring and the class name are correct? to me it looks like the model is T5.

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +    """Embed a string representation of a molecule using a ProtTrans_XLnet model"""
but maybe it's a generic one

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +        # For feature extraction we recommend to use the encoder embedding
comments start lower case

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +        # decoder_embedding = embedding[0].cpu().numpy()
remove commented out code, not needed

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +    def _encode_and_mask(self, sequence: str) -> Tuple[Any, Any]:
do we really need to use `Any`?

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +def selection(scores: List[Dict[str, Any]], k: int = 20) -> List[Any]:
this should leave in `genetic_algorithm.py`

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +def crossover(p1: str, p2: str) -> Tuple[str, str]:
this should leave in `genetic_algorithm.py`

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/processing.py
> +def crossover(p1: str, p2: str) -> Tuple[str, str]:
those `p1` and `p2` do not help as variable names, maybe `a_sequence` and `another_sequence` are better

2022-04-20 07:18 UTC, drugilsberg commented on src/gt4sd/frameworks/enzeptional/tests/test_enzeptional.py
> +# %%
the tests should be using pytest

2022-06-28 13:03 UTC, closed without merging